### ISSUE TITLE
Sintesis - Web Binar

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/sintesis-ElvisS10#2]
[Sistesis - Web Binar.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-ElvisS10/files/7150861/Sistesis.-.Web.Binar.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
